### ISSUE TITLE
git_demographics-organizations-projects.json index name wrong?

### ISSUE THREAD

**Issue by acs** [grimoirelab/panels#2]
The name used in this panel for the enriched index is git_enrich.

Is this correct? Should not be git?

**Comment by dicortazar** [comment]
This should be git indeed. However I'm still in the process of migrating the panels to git...

I'll leave this open till those are migrated.

**Comment by acs** [comment]
@dicortazar any update?

**Comment by dicortazar** [comment]
not a bug anymore, closing the issue, thanks!
