### ISSUE TITLE
URLs in RSS panel are broken

### ISSUE THREAD

**Issue by acs** [grimoirelab/panels#31]
They are pointing to:

https://localhost:8080/restservices/nosql-resources/blog/2017/january/using-golang-to-get-multiple-couchbase-documents-by-key-in-a-single-operation

and it should be

https://blog.couchbase.com/2017/january/using-golang-to-get-multiple-couchbase-documents-by-key-in-a-single-operation

**Comment by dicortazar** [comment]
Indeed RSS links should be standard and not specific of customer. @alpgarcia, do you mind having a look at it? 
@acs, thanks for the report!

**Comment by alpgarcia** [comment]
It seems a problem with link field and not problem with RSS panel. In fact our pre-production dashboard is showing correct URLs, while in couchbase link field shows data pointing to localhost. I guess it could be a problem in data retrieval, please @acs, could you check if we are doing something different in retrieval phase?

**Comment by alpgarcia** [comment]
I've checked the raw index and link information is not correct there, so this issue doesn't correspond to panels repo.

**Comment by dicortazar** [comment]
Thanks @alpgarcia and @acs. Closing this.
