### ISSUE TITLE
Add testing for panels

### ISSUE THREAD

**Issue by alpgarcia** [grimoirelab/panels#94]
Index patterns included in panels should be compared with ES mappings to make sure they will work once imported by Kidash.

* **Input**: JSON file, index name, mapping dictionary.
* **Output**: 
   * differences between index pattern and mapping dictionary, if any.
   
Other tests that could be added on each side:
  * Panels only: 
      * Whether or not they use the specified time field.
      * Analyzed fields not configured as aggregatable (they couldn't be used in buckets).
   * Mappings only:
      * Text fields not having `fielddata:true` (they will be not aggregatable in Kibana)

**Comment by alpgarcia** [comment]
As #103 is now accepted, we should close this and start working in new issues for enhancements/bugs or edit task description to include a task list, which provides a progress bar indicator that might come in handy to keep track of this.

What do you think @dicortazar ?

**Comment by dicortazar** [comment]
That works for me @alpgarcia !

**Comment by alpgarcia** [comment]
> Other tests that could be added on each side:
>
> * Panels only:
>   *  Whether or not they use the specified time field.
>   *  Analyzed fields not configured as aggregatable (they couldn't be used in buckets).
> * Mappings only:
>    * Text fields not having fielddata:true (they will be not aggregatable in Kibana)

Out of the scope of this initial task. To be covered in #108

**Comment by alpgarcia** [comment]
Closing issues as solved in #103
