### ISSUE TITLE
Create indexes schemas for documentation and proper testing

### ISSUE THREAD

**Issue by dicortazar** [grimoirelab/panels#98]
We need a place where the data model is defined. CSV format sounds like a reasonable and easy format to parse. Typically in ElasticSearch mappings some information is specified. For instance, the name of the field, the type, if that's aggregatable, and others. 

I require answers from @jgbarah , @alpgarcia and @sduenas in the following questions as they were commenting in the #99 pull request. What we get from this will be then re-implemented in another branch and the current one will be dismissed.

**Question**: Does CSV format fit your needs?
* Answer: I prefer to use JSON as this is closer to the current technology and even in this case this is technology independent (this basically define field names and types). But CSV works for me as well.

**Question**: For the first iteration and for a standard data model, how many fields do we want to have and which ones?
* Answer: I have initially added the name and the type that are the ones that could be standard in any platform. Fields such as aggregatable are technology dependent.

**Question**: If we have the software to produce the CSV/JSON files, do we need to currently have those?
* Answer: there is a clear need to have the CSV/JSON files to show to others how the data model is, let them know that this can be updated and add a description to all of those that help to identify this.

**Question**: Do we want to produce software as the same time that we produce documentation and CSV/JSON files?
* Answer: as initially the software was producing the CSV files, it sounded reasonable to me to have both in the same commit.

**Comment by dicortazar** [comment]
First version at #99

**Comment by jgbarah** [comment]
About `schema/README.md`: could we be more specific? Now I read:

> Each of the CSV files contains two main columns: name and type. 

I think we should be more conclusive, like:

> Each of the CSV files contain two columnos
> * name
> * type

In fact, I think we need at least some more:

* For some rows, we would need extra information. For example, for strings, I guess we need to specify if they are analyzed or not. For dates, I think we should specify the date format (or maybe specify that for all date fields we use such and such format).
* We need a description field (brief description of the ElasticSearch field).

**Comment by jgbarah** [comment]
I wee you want to reopen the can of worms, @dicortazar ;-) Let's goo for it:

> * Question: Does CSV format fit your needs?
>
>    Answer: I prefer to use JSON as this is closer to the current technology and even in this case this is technology independent (this basically define field names and types). But CSV works for me as well.

That's fine. I prefer YAML, which can  be easily translated to/from JSON if needed, and is much more human readable. But we reached a consensus on JSON, as far as I remember. Maybe I am wrong? The main reason was that you were already working with a spreadsheet, and it was (sort of) working. Or at least that's what I understood. At this point, I would prefer to stick to CSV, and if needed, do a second version with YAML once we're done (I volunteer to translate all the CSV and code we produce for this first version to YAML). If you prefer to reconsider this again, that's fair, but we need to involve at least @acs as well.

> Question: For the first iteration and for a standard data model, how many fields do we want to have and which ones?
>
> Answer: I have initially added the name and the type that are the ones that could be standard in any platform. Fields such as aggregatable are technology dependent.

OK. I just said in #99 that I gave up for now on this. Let's stick to name and type for now if you prefer. If possible, let's at least add a description. I volunteer to fill some of the descriptions in the CSV files as soon as we're done with this.

> Question: If we have the software to produce the CSV/JSON files, do we need to currently have those?
>
>    Answer: there is a clear need to have the CSV/JSON files to show to others how the data model is, let them know that this can be updated and add a description to all of those that help to identify this.

I don't understand the question. I guess all this is for having a format for defining an index. If we agree on that, the rest is just deciding the format (and if it is based on CSV or JSON or whatever). So, although I don't fullly understand you here, I would say we're on the same page.

> Question: Do we want to produce software as the same time that we produce documentation and CSV/JSON files?
>
>    Answer: as initially the software was producing the CSV files, it sounded reasonable to me to have both in the same commit.

Look, again I'm not going to make a problem of this. I just think I would like to have a description of a format with some first implementations of it. If you happen to have written some software that helps to have some of those first descriptions, that's fine. I would upload it in a separate PR, but at this point, I prefer to have that PR ready asap that to stick to that separation.

**Comment by alpgarcia** [comment]
I think we are loosing our goal:
** Defining a enriched index from RAW information coming from Perceval and test that definition against stuff produced by gelk from that definition **

NOTE: Gelk doesn't include any magic, there is a programmer who reads the definition and implements the enrichment there. That's why we want to test gelk results. 

From here, you can read my answers below or just the following paragraph. At the end they are the same thing:

Let's start with a couple of CSVs and some testing, make some quick mistakes, improve things, and carry on making mistakes and improvements. Building the whole model from scratch seems really challenging from my point of view (maybe it is not even possible given the scope of the changes needed to do it, which probably includes a brand new enrichment platform built from scratch).

**Answers**:

> Question: Does CSV format fit your needs?

I actually don't understand why we are back to the beginning with this. But I am going to write the full story to add some context:

---
 _Some months ago I proposed a human readable format to work together with @acs defining and implementing indexes. I decided to use GDocs spreadsheets as a quick way of sharing and structuring information in a flexible way (much better than the old tickets we had for this)._ 

 _Some weeks ago, we definitely saw we needed to add some testing on top of that._ 

---

Is this the best way? Don't think so, but it is the way we are working right now and I don't see any other proposal that fits what @acs and I need (please @acs let me know if I am wrong). The simplest approach: the firts two columns: name and type, and allow other columns for sharing info with @acs. I don't think we are able to define a whole framework from scratch, so let's start adding small parts and I'm sure it will shed light on new improvements as well.

Once this is working, we can add more semantic, even python code if needed (in a java bean shell fashion), or change file format, something I promise I work on if needed as I am sure I can do that "magic" in a couple of hours.

> Question: For the first iteration and for a standard data model, how many fields do we want to have and which ones?

Name, type and the ones I have been using with @acs that includes a column per item type defining where to find field value in the RAW index (and pseudo-code on how to build it) and another additional column for comments. All this stuff in this very first approach is human oriented. More to come, but not now.

> Question: If we have the software to produce the CSV/JSON files, do we need to currently have those?

Don't see the point of this question. We need to define an enriched index and that cannot be done by any software at this moment.

> Question: Do we want to produce software as the same time that we produce documentation and CSV/JSON files?

Depending on the goal of the software. Is it your software useful to build enriched index definition or just to have some quick start files to work with?

I guess it is the latter one and from that point of view, I agree to commit files together with this migration utility.

**Comment by dicortazar** [comment]
> I wee you want to reopen the can of worms, @dicortazar ;-) Let's goo for it:

Not me. I was happy with my PR ;).

>> Question: Does CSV format fit your needs?
>>   Answer: I prefer to use JSON as this is closer to the current technology and even in this case this is technology independent (this basically define field names and types). But CSV works for me as well.

> That's fine. I prefer YAML, which can be easily translated to/from JSON if needed, and is much more human readable. But we reached a consensus on JSON, as far as I remember. Maybe I am wrong? The main reason was that you were already working with a spreadsheet, and it was (sort of) working. Or at least that's what I understood. At this point, I would prefer to stick to CSV, and if needed, do a second version with YAML once we're done (I volunteer to translate all the CSV and code we produce for this first version to YAML). If you prefer to reconsider this again, that's fair, but we need to involve at least @acs as well.

That's ok for me. Let's fix this to CSV file unless @alpgarcia or @sduenas prefer another format for some reason. We can re-open the discussion about CSV or any other format later on.

>> Question: For the first iteration and for a standard data model, how many fields do we want to have and which ones?
>> Answer: I have initially added the name and the type that are the ones that could be standard in any platform. Fields such as aggregatable are technology dependent.

> OK. I just said in #99 that I gave up for now on this. Let's stick to name and type for now if you prefer. If possible, let's at least add a description. I volunteer to fill some of the descriptions in the CSV files as soon as we're done with this.

@jgbarah the requirement about having in the CSV file things like 'aggregatable' are technological dependant (in this case based on ElasticSearch tech.). Do we want that info as well as you and others suggested? If so, do we want this to be linked to a specific technology? I prefer to have a first version of this discussion before I proceed once again with the CSV file.

Just in case and I bring here my own opinion. GrimoireLab currently works with ElasticSearch. I do not foresee any big change in the future. And at most, this will mean that the current tech. will be used by just another stack. We do not have nowadays the requirement of being used in several schemaless databases, but just in one.

Thus, using a typing as close as possible to the current stack we're using. This would help to low the barriers and to avoid producing extra software to translate from 'generic' to ElasticSearch for instance.

>>   Question: If we have the software to produce the CSV/JSON files, do we need to currently have those?
>>    Answer: there is a clear need to have the CSV/JSON files to show to others how the data model is, let them know that this can be updated and add a description to all of those that help to identify this.

> I don't understand the question. I guess all this is for having a format for defining an index. If we agree on that, the rest is just deciding the format (and if it is based on CSV or JSON or whatever). So, although I don't fullly understand you here, I would say we're on the same page.

That was a question by @sduenas as far as I understood him.

>>  Question: Do we want to produce software as the same time that we produce documentation and CSV/JSON files?
>>  Answer: as initially the software was producing the CSV files, it sounded reasonable to me to have both in the same commit.

> Look, again I'm not going to make a problem of this. I just think I would like to have a description of a format with some first implementations of it. If you happen to have written some software that helps to have some of those first descriptions, that's fine. I would upload it in a separate PR, but at this point, I prefer to have that PR ready asap that to stick to that separation.

It seems that having just the CSV files is the way we should work according to what I understood from you all. So, I'll probably produce a new branch just for the CSV files after we close the format discussion.

**Comment by dicortazar** [comment]
Thanks for your comments!

> I think we are loosing our goal:
> ** Defining a enriched index from RAW information coming from Perceval and test that definition against stuff produced by gelk from that definition **

> NOTE: Gelk doesn't include any magic, there is a programmer who reads the definition and implements the enrichment there. That's why we want to test gelk results. 

> From here, you can read my answers below or just the following paragraph. At the end they are the same thing:

> Let's start with a couple of CSVs and some testing, make some quick mistakes, improve things, and carry on making mistakes and improvements. Building the whole model from scratch seems really challenging from my point of view (maybe it is not even possible given the scope of the changes needed to do it, which probably includes a brand new enrichment platform built from scratch).

> **Answers**:

>> Question: Does CSV format fit your needs?

> I actually don't understand why we are back to the beginning with this. But I am going to write the full story to add some context:

> ---
>  _Some months ago I proposed a human readable format to work together with @acs defining and implementing indexes. I decided to use GDocs spreadsheets as a quick way of sharing and structuring information in a flexible way (much better than the old tickets we had for this)._ 

> _Some weeks ago, we definitely saw we needed to add some testing on top of that._ 

> ---

> Is this the best way? Don't think so, but it is the way we are working right now and I don't see any other proposal that fits what @acs and I need (please @acs let me know if I am wrong). The simplest approach: the firts two columns: name and type, and allow other columns for sharing info with @acs. I don't think we are able to define a whole framework from scratch, so let's start adding small parts and I'm sure it will shed light on new improvements as well.

> Once this is working, we can add more semantic, even python code if needed (in a java bean shell fashion), or change file format, something I promise I work on if needed as I am sure I can do that "magic" in a couple of hours.

Oh I opened this as I wanted to be sure that we are all in the same page. I do not want to work on another version and then re-open the discussion about some file type or another.

>> Question: For the first iteration and for a standard data model, how many fields do we want to have and which ones?

> Name, type and the ones I have been using with @acs that includes a column per item type defining where to find field value in the RAW index (and pseudo-code on how to build it) and another additional column for comments. All this stuff in this very first approach is human oriented. More to come, but not now.

The goal of this task is to produce a bunch of CSV/<anyformat> to be used in two ways: data model and testing. The addition of extra comments to be this useful for the enrichment step is another extra.

Let's go to the columns as you mention. I have in the spreadsheet (sorry for not providing a public link here) for Meetup 5 columns: Enriched Field Name, Data Type, Meetup Event (raw item), Attendee and Comment. Let's go now for the Dockerhub backend. I see four columns: Enriched Field Name, Data Type, Docker Image and Event. And let's go for Askbot now: Enriched Field Name, Data Type, Question, Answer and Comment.

As you can see there are different columns depending on the data source (two of them standard across the data sources). What columns do you see as necessary for this first version? @jgbarah is requesting at least the description field and you ( @alpgarcia ) are requesting to have at least another column with info about where the raw info is coming from (this would need more columns as in the previous examples). Comments? (I'm ok with just two columns, but with three or N as well, but I need to know how many and which ones).

>> Question: If we have the software to produce the CSV/JSON files, do we need to currently have those?

> Don't see the point of this question. We need to define an enriched index and that cannot be done by any software at this moment.

We need to define an enriched index, but not manually as we have a bunch of enriched indexes around. I produced the piece of code to avoid writing 30 data sources with 60 fields each ones manually. So there's a specific need for that piece of software, although this does not need to be part of panels. I just thought that this could be interesting to have at some point.

>> Question: Do we want to produce software as the same time that we produce documentation and CSV/JSON files?

> Depending on the goal of the software. Is it your software useful to build enriched index definition or just to have some quick start files to work with?

I guess it is the latter one and from that point of view, I agree to commit files together with this migration utility.  

Ok, so there's another conflict. @jgbarah and @sduenas prefer to separate the PR and you and me prefer to have it together. It's not a big deal, so let's keep rolling.

**Comment by sduenas** [comment]
My concerns were that if we decided to have CVS file, why do we need to have JSON ones, too? Related to this your PR was adding code which didn't match with the purpose of the PR.

The idea of all of this was to have something fast, so we can start to make tests soon. The idea of using CSV was because it seemed the most reasonable thing since @alpgarcia and @acs were already working with it as a way of communicating changes in the schema.

**Comment by dicortazar** [comment]
Thanks for your comments!

> My concerns were that if we decided to have CVS file, why do we need to have JSON ones, too? Related to this your PR was adding code which didn't match with the purpose of the PR.

OK, it seems there is an agreement around CSV in a first step.

> The idea of all of this was to have something fast, so we can start to make tests soon. The idea of using CSV was because it seemed the most reasonable thing since @alpgarcia and @acs were already working with it as a way of communicating changes in the schema.

The communication was actually done using spreadsheets (previously plain text, so using spreadsheets was a great addition). So, let's keep using CSV files and then let's open discussion if needed for further formats.

**Comment by jgbarah** [comment]
OK, let me propose this, which I think could satisfy (to some extent) all of us:

* Let's start with a CVS format **exactly like those @dicortazar was proposing**
* Let's start with a README.md **exactly like the one @dicortazar was proposing**, specifying a first try at that format
* Let's start with some example CVS files **exactly like those @dicortazar was proposing**.

Let's put all of this in a commit, and that's it.

Then, we discuss about the software, the JSON files, other columns, other format, and whatever is appropriate.

@dicortazar, from what I understand, all of us have agreed on this in the comments above. So, if you agree, please change the PR, or open a new one, whatever you may prefer, with that.

Can that be an starting point?

**Comment by dicortazar** [comment]
Yep, I was writing a similar proposal but @jgbarah you were faster!

I'll work on a new branch just with the CSV and README files. Then we iterate.

Thanks for your comments and time!

**Comment by jgbarah** [comment]
Great! Waiting for the new proposal ;-)

**Comment by alpgarcia** [comment]
Solved at CSVs are now merged in the repo.
